### ISSUE TITLE
SKKプラス辞書(独自形式辞書)の開発と配布について

### ISSUE THREAD

**Issue by coexe** [skk-users-jp/skk-users-jp.github.com#8]
(ちょっとどこに書けばいいのかわからなかったので、別の場所に書くべきでしたら移動します。Twitterのほうがいいですかね……？)

独自形式のSKK辞書をずっと自前のWebページで管理していたのですが、一人では管理しきれなくなってきたのでGitHubで開発してSKK-users.jpで配布、みたいな形をやってみたいと思っています。

SKK-usersで配布したいなと思っているのはこの辞書です。
・SKKプラス送りがな補正辞書 通常ローマ字かな変換向け
・SKKプラス送りがな補正辞書 AZIK/ACT系ローマ字かな変換向け

上記のうち通常ローマ字かな変換向けの雛形は現在、
http://coexe.web.fc2.com/skk-plus.txt
に置いてあります。
AZIK系については本格的なものはこちら手が出せないので適任者に声をかけて呼び込みたいと思ってます。
まずはこれをSKK-users.jpでやってもよいかについてみなさんの意見を頂きたく。

**Comment by zonuexe** [comment]
@coexe 
CC0だったので、とりあえず叩き台として勝手にインポートしておきました。
https://github.com/skk-users-jp/skk-plus-dic

(いちおう以下のURLで配信できますが、HTTPSじゃないのでこのまま利用すべきか悩んでます)
http://skk-users.jp/skk-plus-dic/skk-plus.txt

**Comment by coexe** [comment]
ありがとう！そしてありがとう！
まだこちらのインストーラはHTTPSが喋れないのでhttpの口が残してあると助かります。
AZIK向け辞書についてはいま担当の方に声かけているところです。
